---
- name: Provision JMeter Infrastructure
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create JMeter VM instance
      google.cloud.gcp_compute_instance:
        name: jmeter-generator
        machine_type: e2-standard-2
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_cred_file }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts"
              disk_size_gb: 10
        network_interfaces:
          - access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
      register: vm_instance

    - name: Wait for SSH to be ready
      wait_for:
        host: "{{ vm_instance.networkInterfaces[0].accessConfigs[0].natIP }}"
        port: 22
        delay: 10
        timeout: 300

    - name: Dynamically add the VM to inventory
      add_host:
        name: "{{ vm_instance.networkInterfaces[0].accessConfigs[0].natIP }}"
        groups: jmeter_vm
        ansible_ssh_user: "vagrant"
        ansible_ssh_private_key_file: "~/.ssh/id_rsa"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

- name: Install JMeter on the VM
  hosts: jmeter_vm
  become: true
  gather_facts: false
  vars:
    jmeter_version: "5.6.3"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 17 (Required for JMeter)
      apt:
        name: openjdk-17-jre-headless
        state: present

    - name: Download JMeter
      get_url:
        url: "https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-{{ jmeter_version }}.tgz"
        dest: "/tmp/jmeter.tgz"

    - name: Create JMeter directory
      file:
        path: /opt/jmeter
        state: directory
        mode: '0755'

    - name: Unarchive JMeter
      unarchive:
        src: "/tmp/jmeter.tgz"
        dest: "/opt/jmeter"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Add JMeter to system PATH
      lineinfile:
        path: /etc/profile.d/jmeter.sh
        line: 'export PATH=$PATH:/opt/jmeter/bin'
        create: yes
