/*import { io } from "socket.io-client";


const socketAdmin = io("http://localhost:5000", {
  auth: { client_type: "web",
          jwt_token: 'eyJhbGciOiJFUzI1NiIsImtpZCI6ImNhLWtleS0xIiwidHlwIjoiSldUIn0.eyJpc3MiOiJNeUxvY2FsQXVjdGlvbkNBIiwic3ViIjoiNjM3MDhiZWUzYWYyODc4YjQ5MGRjN2I2NDcwODcyZTFkZTJmY2M3ZDlkZTk5MDQ3ZjJjOGQ4YmFhNzAyY2NmZiIsImF1ZCI6IkF1Y3Rpb25OZXR3b3JrIiwiZXhwIjoxNzYzODA5MTQ1LCJuYmYiOjE3NjM4MDU1NDUsImlhdCI6MTc2MzgwNTU0NSwianRpIjoiOWIyY2YyMjEtODMyZi00YjQ5LTgzYjQtMzJhNjZiODE2MmNjIn0.lIvfGOarKffcDwuovwoAHNa6SrDj5U3FnoEF5TZLhBCoZclZeTJ8C0xHUudk56JVCK51VyA24QlK1q29OgnALg',
          certificate: '-----BEGIN CERTIFICATE-----\nMIIBkTCCATigAwIBAgIUXEnI7fuSJrcpq8DJD91geCIq5AMwCgYIKoZIzj0EAwIw\nGzEZMBcGA1UECgwQTXlMb2NhbEF1Y3Rpb25DQTAeFw0yNTExMjIwOTU5MDNaFw0y\nNjExMjIwOTU5MDNaMGUxCzAJBgNVBAYTAlBUMQ4wDAYDVQQIDAVCcmFnYTEOMAwG\nA1UEBwwFQnJhZ2ExFDASBgNVBAoMC1AyUCBBdWN0aW9uMSAwHgYDVQQDDBdncnVw\nb3NldGUubWNzLnVtaW5oby5wdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHiV\nY3Xz2lADgU97K55k+xsKTr+AqR1+7yYcTNp9zHv4RJI5SwkM/sy+DXNfw7tn6qSN\n+qv6u6Oosh3SuSd+IHSjEDAOMAwGA1UdEwEB/wQCMAAwCgYIKoZIzj0EAwIDRwAw\nRAIgVMYfUMDOSbuvdN8EoeY+ZxwqahLMhi7dJIG+QFhvANwCIE55TTX9uheb/ah3\n3+cfaE2YTWCXS7Eo2TV2uyfC+p6G\n-----END CERTIFICATE-----\n',
        },
});

export default socketAdmin;
*/